{"name": "Test job countries from the anahr website against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured", "trace": "get_job_details = ((['Inginer Proiectant', 'Asistent Comercial', 'Inginer Instalații pentru Construcții', 'Responsabil Recepție', 'Manag...r', 'Anahr', 'Anahr', 'Anahr', 'Anahr', ...], ['on-site', 'on-site', 'on-site', 'on-site', 'on-site', 'on-site', ...]))\n\n    @pytest.mark.regression\n    @pytest.mark.API\n    def test_anahr_country_api(get_job_details):\n        allure.dynamic.title(f\"Test job countries from the {company_name} website against Peviitor API Response\")\n    \n        scraped_jobs_data, peviitor_jobs_data = get_job_details\n        with allure.step(\"Step 1: Get job countries and titles from the scraper\"):\n            job_countries_scraper = scraped_jobs_data[2]\n            job_titles_scraper = scraped_jobs_data[0]\n    \n        with allure.step(\"Step 2: Get job countries and titles from the Peviitor API\"):\n            job_countries_peviitor = peviitor_jobs_data[2]\n            job_titles_peviitor = peviitor_jobs_data[0]\n    \n        with allure.step(\"Step 3: Compare job countries from scraper response against Peviitor API Response\"):\n            allure.attach(f\"Expected Results: {job_countries_scraper}\", name=\"Expected Results\")\n            allure.attach(f\"Actual Results: {job_countries_peviitor}\", name=\"Actual Results\")\n>           TestUtils().check_job_countries(job_countries_scraper,job_titles_scraper, job_countries_peviitor, job_titles_peviitor)\n\ntests/Test_API_Suite/test_anahr.py:75: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <tests.utils.TestUtils object at 0x7f19fa89ba90>\nexpected_countries = ['Romania', 'Romania', 'Romania', 'Romania', 'Romania', 'Romania', ...]\nactual_countries = ['Inginer Proiectant', 'Asistent Comercial', 'Inginer Instalații pentru Construcții', 'Responsabil Recepție', 'Manager de Producție', 'IT Manager', ...]\njob_titles_scraper = ['Romania', 'Romania', 'Romania', 'Romania', 'Romania', 'Romania', ...]\napi_job_titles = ['Reprezentant Vânzări Timișoara', 'Inginer Proiectant', 'Asistent Comercial', 'Inginer Instalații pentru Construcții', 'Responsabil Recepție', 'Manager de Producție', ...]\n\n    def check_job_countries(self, expected_countries, actual_countries, job_titles_scraper, api_job_titles):\n        if not expected_countries:\n            msg = f\"Scraper is not grabbing any job countries\"\n            allure.step(msg)\n            raise AssertionError(msg)\n    \n        msg = \"An unknown error occured\"\n    \n        # Check job countries from scraper against the peviitor api\n        scraper_actual_countries, scraper_job_titles = self.get_different_items(expected_countries, actual_countries, job_titles_scraper)\n    \n        if scraper_actual_countries:\n            msg = f\"Peviitor is missing job countries for the following job titles: {scraper_job_titles}\"\n            allure.step(msg)\n            raise AssertionError(msg)\n        else:\n            # Check job countries from peviitor against the scraper response\n            peviitor_actual_countries, peviitor_job_titles = self.get_different_items(actual_countries, expected_countries, api_job_titles)\n            if peviitor_actual_countries:\n                msg = f\"Peviitor is having extra job countries for the following titles: {peviitor_job_titles}\"\n                allure.step(msg)\n                raise AssertionError(msg)\n    \n        allure.step(msg)\n>       assert expected_countries == actual_countries, msg\nE       AssertionError: An unknown error occured\n\ntests/utils.py:178: AssertionError"}, "steps": [{"name": "Step 1: Get job countries and titles from the scraper", "status": "passed", "start": 1718773865536, "stop": 1718773865536}, {"name": "Step 2: Get job countries and titles from the Peviitor API", "status": "passed", "start": 1718773865536, "stop": 1718773865536}, {"name": "Step 3: Compare job countries from scraper response against Peviitor API Response", "status": "failed", "statusDetails": {"message": "AssertionError: An unknown error occured\n", "trace": "  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_anahr.py\", line 75, in test_anahr_country_api\n    TestUtils().check_job_countries(job_countries_scraper,job_titles_scraper, job_countries_peviitor, job_titles_peviitor)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/utils.py\", line 178, in check_job_countries\n    assert expected_countries == actual_countries, msg\n"}, "attachments": [{"name": "Expected Results", "source": "3d5e8f2a-d4d0-4101-9169-49f857d4bb73-attachment.attach"}, {"name": "Actual Results", "source": "4223db44-5a2c-4c29-bb78-5de07ae43d4b-attachment.attach"}], "start": 1718773865536, "stop": 1718773865536}], "start": 1718773865536, "stop": 1718773865536, "uuid": "05e1dde3-c255-4a33-90f8-df7286406746", "historyId": "50937ac439f5f8d053d6fa34f5434bd9", "testCaseId": "50937ac439f5f8d053d6fa34f5434bd9", "fullName": "Test_API_Suite.test_anahr#test_anahr_country_api", "labels": [{"name": "tag", "value": "API"}, {"name": "tag", "value": "regression"}, {"name": "parentSuite", "value": "Test_API_Suite"}, {"name": "suite", "value": "test_anahr"}, {"name": "host", "value": "fv-az779-853"}, {"name": "thread", "value": "2227-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_API_Suite.test_anahr"}]}