{"uuid": "55956954-05bf-49ae-9dfc-d609800e40c0", "children": ["d2fb8a3f-94a0-4cef-8ad2-baead198f2b1", "9e85811f-d2a0-4f6c-9095-3bb1420ce562", "1c3fb77b-3b0a-4d6d-85cc-5dde53d89f7c", "0ea11063-fbcb-4839-ba7e-228972917154", "4355979a-0da1-48fd-8b47-1e04f7a4a35f"], "befores": [{"name": "get_job_details", "status": "broken", "statusDetails": {"message": "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='consultmed.ro', port=443): Max retries exceeded with url: /consultmed-clinica-diabet-nutritie-iasi/cariere/ (Caused by NameResolutionError(\"<urllib3.connection.HTTPSConnection object at 0x7f691390de40>: Failed to resolve 'consultmed.ro' ([Errno -3] Temporary failure in name resolution)\"))\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/tests/Test_API_Suite/test_consultmed.py\", line 14, in get_job_details\n    scraper_data = consultmedScraper().return_data()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/consultmed.py\", line 42, in return_data\n    self.get_response()\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/consultmed.py\", line 25, in get_response\n    self.get_content(self.url)\n  File \"/home/runner/work/RaresTestHub/RaresTestHub/sites/website_scraper_bs4.py\", line 34, in get_content\n    response = requests.get(url, headers=self.DEFAULT_HEADERS, verify=False)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 73, in get\n    return request(\"get\", url, params=params, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/requests/adapters.py\", line 519, in send\n    raise ConnectionError(e, request=request)\n"}, "start": 1711084249388, "stop": 1711084259407}], "start": 1711084249388, "stop": 1711084259945}